# mysql
spring:
  datasource:
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/communitypension?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: 948524

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.community.bean
server:
  port: 9001
